### PR TITLE
Set RRAs for all of Mozilla to Steph and Gene

### PR DESCRIPTION
**Pull request by gene1wood**

### CODE REVIEW

**Review by arroway — APPROVED** [review]
Looks good!
Out of curiosity, what does the field "needinfo" set to jclaudius do? (line 4) I couldn't see it in use in an actual bug.

**Comment by claudijd** [comment]
@arroway I don't know why that is there, from my perspective it can be removed as I have no real interest here outside of IR or specific product security strategy efforts, of which I'm already plugged in where I need to be.

**Comment by gene1wood** [comment]
I've deployed this

**Comment by gene1wood** [comment]
Turns out the way this project works, you're not supposed to deploy things like this, but instead the service pulls from this repo every 15 minutes. I've reverted my deployment so it can deploy itself.

The result was that I broke this on Jan 11 and it's been broken up through today.

**Pull request merged**
